service: Wait for LXD members to be ready after join
This is to prevent the following error from happening in case resources are getting deployed right after creating the MicroCloud:
Error: Failed instance creation: Fetch project database object: Failed to fetch from projects table: Failed to fetch from projects table: Failed to fetch from projects table: sql: transaction has already been committed or rolled back

Signed-off-by: Julian Pelizäus <julian.pelizaeus@canonical.com>
(cherry picked from commit 36f8c24a7198d32dacf2aa77b8eee5a3112b7246)